name: preschool-erp
region: nyc

# Database - Managed MySQL
databases:
  - name: preschool-db
    engine: MYSQL
    version: "8"
    production: true
    cluster_name: preschool-db-cluster

# Backend API Service
services:
  - name: backend
    github:
      repo: venudadi/preschoold-erp
      branch: main
      deploy_on_push: true
    source_dir: /backend
    build_command: npm ci --legacy-peer-deps
    run_command: node index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 5001
    health_check:
      http_path: /api/health
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5001"
      - key: DB_HOST
        value: ${preschool-db.HOSTNAME}
      - key: DB_PORT
        value: ${preschool-db.PORT}
      - key: DB_USER
        value: ${preschool-db.USERNAME}
      - key: DB_PASSWORD
        value: ${preschool-db.PASSWORD}
      - key: DB_NAME
        value: ${preschool-db.DATABASE}
      - key: JWT_SECRET
        type: SECRET
        value: your_jwt_secret_change_this
      - key: DATABASE_URL
        value: ${preschool-db.DATABASE_URL}

# Frontend Static Site
static_sites:
  - name: frontend
    github:
      repo: venudadi/preschoold-erp
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    build_command: npm ci --legacy-peer-deps && npm run build
    output_dir: /dist
    environment_slug: node-js
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    envs:
      - key: VITE_API_URL
        value: ${backend.PUBLIC_URL}
    routes:
      - path: /

# Jobs for migrations (run on deploy)
jobs:
  - name: migrations
    kind: PRE_DEPLOY
    github:
      repo: venudadi/preschoold-erp
      branch: main
      deploy_on_push: true
    source_dir: /backend
    build_command: npm ci --legacy-peer-deps
    run_command: npm run migrate:clean
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: ${preschool-db.HOSTNAME}
      - key: DB_PORT
        value: ${preschool-db.PORT}
      - key: DB_USER
        value: ${preschool-db.USERNAME}
      - key: DB_PASSWORD
        value: ${preschool-db.PASSWORD}
      - key: DB_NAME
        value: ${preschool-db.DATABASE}
